# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :project do

    # checkout release branch
    ensure_git_status_clean

    # clear data
    xcclean(
      scheme: "GBShop",
      workspace: "GBShop.xcworkspace"
    )
    
    # update a dependencies
    cocoapods(
      use_bundle_exec: false
    )

    # run tests
    run_tests(
      workspace: "GBShop.xcworkspace",
      scheme: "GBShop",
      device: "iPhone 14 Pro Max",
      clean: false,
      code_coverage: true,
      open_report: true
    )

    # make screenshots
    capture_ios_screenshots

    # increment build number
    increment_build_number
    set_info_plist_value(
      path: "./GBShop/Environments/Info.plist",
      key: "CFBundleShortVersionString",
      value: get_build_number(xcodeproj: "GBShop.xcodeproj"))

    # git_add
    git_add(path: [
      "./GBShop.xcodeproj/project.pbxproj",
      "./GBShop/Environments/Info.plist"
    ])
    git_commit(
      path: [
        "./GBShop.xcodeproj/project.pbxproj",
        "./GBShop/Environment/Info.plist"],
      message: "build project, all test success executed, up build version"
    )

  end
end
