# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'GBShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GBShop
  pod 'Alamofire', '5.6.1'
  pod 'RealmSwift', '10.36.0'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase/Crashlytics'

  target 'GBShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GBShopUITests' do
    # Pods for testing
  end

end
